RWCTF2018/Bookhub/bookhub/views/book.py
import flask
from flask_login import login_required, login_user, current_user
from bookhub import app, db
from bookhub.forms import BookForm
from bookhub.models import User, Book


book_blueprint = flask.Blueprint('book', __name__, template_folder='templates')


@book_blueprint.route('/')
def index():
    try:
        page = int(flask.request.args.get('page', 1))
    except ValueError:
        page = 1

    object_list = Book.query.order_by(Book.created_at.desc()).paginate(page, per_page=10, error_out=False)
    object_list.module_name = 'book.index'
    return flask.render_template('index.html', object_list=object_list, is_debug=app.debug)


@book_blueprint.route('/admin/')
@login_required
def admin():
    try:
        page = int(flask.request.args.get('page', 1))
    except ValueError:
        page = 1

    object_list = Book.query.order_by(Book.created_at.desc()).paginate(page, per_page=10, error_out=False)
    object_list.module_name = 'book.admin'
    return flask.render_template('admin.html', object_list=object_list)


@book_blueprint.route('/admin/add/', methods=['GET', 'POST'])
@login_required
def add():
    form = BookForm(data=flask.request.data)
    if form.validate_on_submit():
        book = Book()
        form.populate_obj(book)
        db.session.add(book)
        db.session.commit()
        return flask.redirect(flask.url_for('book.admin'))

    return flask.render_template('add.html', form=form)


@book_blueprint.route('/admin/edit/<int:id>/', methods=['GET', 'POST'])
@login_required
def edit(id):
    book = Book.query.filter_by(id=id).first_or_404()
    form = BookForm(data=flask.request.data, obj=book)
    if form.is_submitted() and flask.request.form.get('delete', None) is not None:
        db.session.delete(book)
        db.session.commit()
        return flask.redirect(flask.url_for('book.admin'))
    elif form.validate_on_submit():
        form.populate_obj(book)
        db.session.commit()
        return flask.redirect(flask.url_for('book.admin'))

    return flask.render_template('edit.html', form=form)

RWCTF2018/Bookhub/bookhub/views/user.py
import flask
import redis
from flask_login import login_required, login_user, current_user, logout_user
from bookhub import app, db, rds
from bookhub.forms import LoginForm, UserForm
from bookhub.models import User, Book
from bookhub.helper import get_remote_addr


user_blueprint = flask.Blueprint('user', __name__, template_folder='templates')


@user_blueprint.route('/login/', methods=['GET', 'POST'])    #可以接受GET/POST兩種方式
def login():
    form = LoginForm(data=flask.request.data)
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        login_user(user, remember=form.remember_me.data)

        return flask.redirect(flask.url_for('book.admin'))

    return flask.render_template('login.html', form=form)


@user_blueprint.route('/admin/logout/')
@login_required
def logout():
    logout_user()
    return flask.redirect(flask.url_for('user.login'))


if app.debug:
    """
    For CTF administrator, only running in debug mode
    """

    @user_blueprint.route('/admin/system/')
    @login_required
    def system():
        """


        :return:
        """

        ip_address = get_remote_addr()
        user_count = User.query.count()
        book_count = Book.query.count()

        return flask.render_template('system.html',
                                     ip_address=ip_address,
                                     user_count=user_count,
                                     book_count=book_count
                                     )

    @user_blueprint.route('/admin/system/change_name/', methods=['POST'])
    @login_required
    def change_name():
        """
        change username

        :return: json
        """

        user = User.query.get(current_user.id)
        form = UserForm(obj=user)
        if form.validate_on_submit():
            form.populate_obj(user)

            db.session.commit()
            return flask.jsonify(dict(status='success'))
        else:
            return flask.jsonify(dict(status='fail', errors=form.errors))


    @login_required
    @user_blueprint.route('/admin/system/refresh_session/', methods=['POST'])
    def refresh_session():
        """
        delete all session except the logined user

        :return: json
        """

        status = 'success'
        sessionid = flask.session.sid
        prefix = app.config['SESSION_KEY_PREFIX']

        if flask.request.form.get('submit', None) == '1':
            try:
                rds.eval(rf'''
                local function has_value (tab, val)
                    for index, value in ipairs(tab) do
                        if value == val then
                            return true
                        end
                    end
                
                    return false
                end
                
                local inputs = {{ "{prefix}{sessionid}" }}
                local sessions = redis.call("keys", "{prefix}*")
                
                for index, sid in ipairs(sessions) do
                    if not has_value(inputs, sid) then
                        redis.call("del", sid)
                    end
                end
                ''', 0)
            except redis.exceptions.ResponseError as e:
                app.logger.exception(e)
                status = 'fail'

        return flask.jsonify(dict(status=status))

RWCTF2018/Bookhub/bookhub/templates/_base.html
<html>
<head>
<meta charset="utf-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
<title>pwnhub_6672</title>
<link href="https://cdn.bootcss.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet">
{% block addstyle %}{% endblock %}
</head>
<body>
    {% block body %}{% endblock %}
    {% block addscript %}{% endblock %}
</body>
</html>

RWCTF2018/Bookhub/bookhub/templates/_form.html
{% macro render(form) -%}

{%- for field in form -%}
{%- if field.type in ['CSRFTokenField', 'HiddenField'] -%}
  {{ field() }}
{%- elif field.is_show and not field.is_show() -%}
{%- else -%}
  <div class="form-group">
    <label class="{% if field.errors %}text-danger{% endif %}">{{ field.label.text }}</label>
    {{ field(class_="form-control") }}
    {% if field.errors or field.help_text %}
        <small class="form-text {% if field.errors %}text-danger{% else %}text-muted{% endif %}">
        {% if field.errors %}
          {{ field.errors | first }}
        {% else %}
          {{ field.help_text }}
        {% endif %}
        </small>
    {%- endif -%}
  </div>
{%- endif -%}
{%- endfor -%}
{% endmacro %}

RWCTF2018/Bookhub/bookhub/templates/_pagination.html
{% macro render(pagenav) -%}

{% if pagenav.total > 0 %}
<ul class="pagination">
    <li class="page-item {% if not pagenav.has_prev %}disabled{% endif %}"><a class="page-link" href="{{ url_for(pagenav.module_name, page=pagenav.prev_num) }}">&laquo;</a></li>
  {%- for page in pagenav.iter_pages() -%}
  {% if page %}
    {% if page != pagenav.page -%}
    <li class="page-item"><a class="page-link" href="{{ url_for(pagenav.module_name, page=page) }}">{{ page }}</a></li>
    {%- else -%}
        <li class="page-item active"><a class="page-link" href="javascript:;">{{ page }}</a></li>
    {%- endif %}
  {% else -%}
      <li class="page-item disabled"><a class="page-link" href="javascript:;">&hellip;</a></li>
  {%- endif %}
  {%- endfor -%}
  <li class="page-item {% if not pagenav.has_next %}disabled{% endif %}"><a class="page-link" href="{{ url_for(pagenav.module_name, page=pagenav.next_num) }}">&raquo;</a></li>
</ul>
{% endif %}

{%- endmacro %}

RWCTF2018/Bookhub/bookhub/templates/add.html
{% extends '_base.html' %}
{% import '_form.html' as f %}

{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h1>Book Management</h1>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <form method="post" enctype="application/x-www-form-urlencoded">
                {{ f.render(form) }}
                <div class="form-group float-right">
                    <button type="button" class="btn btn-default" onclick="history.back(-1)">Go back</button>
                    <button type="submit" class="btn btn-primary">Submit</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

RWCTF2018/Bookhub/bookhub/templates/admin.html
{% extends '_base.html' %}
{% import "_pagination.html" as pagation %}

{% block body %}
<div>
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h1>Book Management</h1>
            </div>
        </div>
        <div class="row">
            <div class="col">
                <div class="alert alert-success" role="alert"><span><strong>Hello, {{ current_user.username }}</strong>.</span>
                    <a href="{{ url_for('user.logout') }}">Click here</a> to logout.</div>
            </div>
        </div>
        <div class="row" style="margin-bottom: 10px">
            <div class="col"><a class="btn btn-primary float-right" href="{{ url_for('book.add') }}">Add a new book</a></div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="table-responsive">
                    <table class="table table-hover">
                        <thead>
                            <tr>
                                <th>Book cover</th>
                                <th width="20%">Book title</th>
                                <th>Book description</th>
                                <th>Edit</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for object in object_list.items %}
                            <tr>
                                <td><img src="{{ object.img }}" alt="{{ object.title }}" width="100"></td>
                                <td>{{ object.title }}</td>
                                <td>{{ object.description }}</td>
                                <td><a class="btn btn-outline-primary btn-sm" href="{{ url_for('book.edit', id=object.id) }}" role="button">Edit</a></td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <nav class="float-right">
                    {{ pagation.render(object_list) }}
                </nav>
            </div>
        </div>
    </div>
</div>
<div></div>
{% endblock %}

RWCTF2018/Bookhub/bookhub/templates/edit.html
{% extends '_base.html' %}
{% import '_form.html' as f %}

{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h1>Book Management</h1>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <form method="post" enctype="application/x-www-form-urlencoded">
                {{ f.render(form) }}
                <div class="form-group float-right">
                    <button type="button" class="btn btn-default" onclick="history.back(-1)">Go back</button>
                    <button type="submit" name="delete" class="btn btn-danger">Delete</button>
                    <button type="submit" class="btn btn-primary">Submit</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

RWCTF2018/Bookhub/bookhub/templates/error.html
{% extends '_base.html' %}

{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h1>Error Page</h1>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <div role="alert" class="alert alert-danger">
                <h4 class="alert-heading">{{ heading | default('Something goes wrong~') }}</h4>
                <p>{{ detail }}
                    Please <a href="{{ jump | default('javascript:history.back(-1)') }}">click here</a> to process.
                </p>
            </div>
        </div>
    </div>
</div>
{% endblock %}

RWCTF2018/Bookhub/bookhub/templates/index.html
{% extends '_base.html' %}
{% import "_pagination.html" as pagation %}

{% block body %}
<div>
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h1>Bookhub</h1>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="table-responsive">
                    <table class="table table-hover">
                        <thead>
                            <tr>
                                <th>Book cover</th>
                                <th width="20%">Book title</th>
                                <th>Book description</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for object in object_list.items %}
                            <tr>
                                <td><img src="{{ object.img }}" alt="{{ object.title }}" width="100"></td>
                                <td>{{ object.title }}</td>
                                <td>{{ object.description }}</td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <nav class="float-right">
                    {{ pagation.render(object_list) }}
                </nav>
            </div>
        </div>
    </div>
</div>
<div></div>
{% endblock %}

{% block addscript %}
{% if is_debug %}
<script src="//cdn.bootcss.com/jquery/3.3.1/jquery.min.js"></script>
<script src="//cdn.bootcss.com/mouse0270-bootstrap-notify/3.1.7/bootstrap-notify.min.js"></script>
<script>
window.onload = function(ev) {
    $.notify({
      message: 'The bookhub is running in debug mode, which can lead to security issues!'
    }, {
        type: 'danger',
        placement: {
          from: "top",
          align: "center"
        },
        delay: 0
    });
};
</script>
{% endif %}

{% endblock %}

{% block addstyle %}

{% if is_debug %}
<style>
[data-notify="progressbar"] {
	margin-bottom: 0px;
	position: absolute;
	bottom: 0px;
	left: 0px;
	width: 100%;
	height: 5px;
}
</style>
{% endif %}

{% endblock %}

RWCTF2018/Bookhub/bookhub/templates/login.html
{% extends '_base.html' -%}

{% block body %}
<div class="d-flex flex-column justify-content-center" id="login-box">
	<div class="login-box-header">
		<h4>Login</h4>
	</div>
	<form method="post">
    {{ form.csrf_token }}
		<div class="name-login">
			<input type="text" required placeholder="Username" name="username" class="name-input form-control"/>
			{% if form.errors.username %}
      <div role="alert" class="alert alert-danger">{{ form.errors.username | first }}</div>
			{% endif %}
      <input type="password" required placeholder="Password" name="password" class="password-input form-control"/>
			{% if form.errors.password %}
      <div role="alert" class="alert alert-danger">{{ form.errors.password | first }}</div>
			{% endif %}
      </div>
		<div class="submit-row">
			<button class="btn btn-primary btn-block box-shadow" type="submit" id="submit-id-submit">Login</button>
			<div class="d-flex justify-content-between">
				<div class="form-check form-check-inline" id="form-check-rememberMe">
					<input type="checkbox" name="remember_me" class="form-check-input" id="formCheck-1"/><label for="formCheck-1" class="form-check-label"><span class="label-text">Remember Me</span></label>
				</div>
			</div>
		</div>
	</form>
	<div id="login-box-footer">
		<p>
			Admin panel login...
		</p>
	</div>
</div>
{% endblock %}

{% block addscript %}
<link rel="stylesheet" href="/static/css/login.css"/>
{% endblock %}

RWCTF2018/Bookhub/bookhub/templates/system.html
{% extends '_base.html' %}

{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h1>System Management</h1>
        </div>
    </div>
    <div class="row">
            <div class="col">
                <div class="alert alert-success" role="alert"><span><strong>Hello, {{ current_user.username }}</strong>.</span>
                    <a href="{{ url_for('user.logout') }}">Click here</a> to logout.</div>
            </div>
        </div>
    <div class="row">
        <div class="col">
            <div class="table-responsive table-borderless">
                <table class="table table-bordered">
                    <tbody>
                        <tr>
                            <td>Your username</td>
                            <td>{{ current_user.username }}</td>
                        </tr>
                        <tr>
                            <td>Your IP address</td>
                            <td>{{ ip_address }}</td>
                        </tr>
                        <tr>
                            <td>Number of users</td>
                            <td>{{ user_count }}</td>
                        </tr>
                        <tr>
                            <td>Number of books</td>
                            <td>{{ book_count }}</td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <hr />
            <label>Change your username: </label>
            <div class="input-group mb-3">
              <input type="text" class="form-control" id="change_name_value" value="{{ current_user.username }}">
              <div class="input-group-append">
                <button class="btn btn-outline-secondary" id="change_name" type="button">Change</button>
              </div>
            </div>

            <button class="btn btn-outline-secondary" id="clear_session" type="button">
              Clear all session except yours
            </button>
        </div>
    </div>
</div>
{% endblock %}

{% block addscript %}
<script src="//cdn.bootcss.com/axios/0.18.0/axios.min.js"></script>
<script>
window.addEventListener('load', function (ev) {
      document.querySelector('#change_name').addEventListener('click', function (ev1) {
          const params = new URLSearchParams();
          params.append('username', document.querySelector('#change_name_value').value);
          axios({
              method: 'post',
              url: '{{ url_for('user.change_name') }}',
              data: params,
              headers: {
                  'X-CSRFToken': '{{ csrf_token() }}'
              }
          }).then(function (response) {
              if (response.data.status === 'success') {
                  location.reload()
              } else {
                  alert(response.data.errors['username'][0])
              }
          }).catch(function (error) {
              console.log(error)
          })
      });

      document.querySelector('#clear_session').addEventListener('click', function (ev1) {
          const params = new URLSearchParams();
          params.append('submit', '1');
          axios({
              method: 'post',
              url: '{{ url_for('user.refresh_session') }}',
              data: params,
              headers: {
                  'X-CSRFToken': '{{ csrf_token() }}'
              }
          }).then(function (response) {
              if (response.data.status === 'success') {
                  location.reload()
              }
          }).catch(function (error) {
              console.log(error)
          })
      });
})
</script>
{% endblock %}